swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transactions/{compteId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Read all Transactions
      description: API for read all transactions
      parameters:
        - in: path
          name: compteId
          description: ID of compte
          required: true
          type: integer
          format: int64
        - in: header
          name: token
          description: token de connexion
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transactions récupérées avec succès
          schema:
            $ref: "#/definitions/transactionsResponse"

        "400":
          description: Champs invalides
        "401":
          description: Non autorisé
        "500":
          description: Erreur interne du serveur
  /transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Read a Transaction
      description: API for to modify a transactions
      parameters:
        - in: path
          name: id
          description: ID of transaction
          required: true
          type: integer
          format: int64
        - in: header
          name: token
          description: token de connexion
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Réponse réussie
          schema:
            $ref: "#/definitions/transactionResponse"
        "400":
          description: Champs invalides
        "401":
          description: Non autorisé
        "500":
          description: Erreur interne du serveur
  /transaction/info/{id}:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Modify a information of transactions
      description: API for modify a information of transactions
      parameters:
        - in: path
          name: id
          description: ID of transaction
          required: true
          type: integer
          format: int64
        - in: header
          name: token
          description: token de connexion
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Réponse réussie
          schema:
            $ref: "#/definitions/transactionInfoResponse"
        "400":
          description: Champs invalides
        "401":
          description: Non autorisé
        "500":
          description: Erreur interne du serveur
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  transactionsResponse:
    type: object
    properties:
      id:
        type: integer
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
        format: double
      balance:
        type: number
        format: double
      details:
        type: object
        properties:
          transaction-type:
            type: string
          category:
            type: string
          note:
            type: string
  transactionResponse:
    type: object
    properties:
      id:
        type: integer
        example: 1
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
        format: double
      balance:
        type: number
        format: double
      details:
        type: object
        properties:
          transaction-type:
            type: string
          category:
            type: string
          note:
            type: string
  transactionInfoResponse:
    type: object
    properties:
      id:
        type: integer
        example: 1
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
        format: double
      balance:
        type: number
        format: double
      details:
        type: object
        properties:
          transaction-type:
            type: string
          category:
            type: string
          note:
            type: string
